2023-03-13 12:02:41,938 - INFO - Iniciamos el proceso
2023-03-13 12:02:41,942 - ERROR - Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
Traceback (most recent call last):
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/compat/_optional.py", line 141, in import_optional_dependency
    module = importlib.import_module(name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'openpyxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sergioretuerto/Documents/Projects/attsf/attsf-ordenes-de-trabajo/app/log_example.py", line 10, in <module>
    df_camiones = pd.read_excel(
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 482, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1695, in __init__
    self._reader = self._engines[engine](self._io, storage_options=storage_options)
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/io/excel/_openpyxl.py", line 556, in __init__
    import_optional_dependency("openpyxl")
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/compat/_optional.py", line 144, in import_optional_dependency
    raise ImportError(msg)
ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.
2023-03-13 12:02:57,160 - INFO - Iniciamos el proceso
2023-03-13 12:02:57,552 - INFO - Leido el fichero BASE DE DATOS 2022 PRUEBA.xlsx
2023-03-13 12:15:22,843 - ERROR - Iniciamos el proceso
2023-03-13 12:15:23,758 - INFO - Leido el fichero BASE DE DATOS 2022 PRUEBA.xlsx
2023-03-13 12:15:33,910 - INFO - Leido el fichero BASE DE DATOS 2022 PRUEBA.xlsx
2023-03-13 12:15:52,420 - INFO - Iniciamos el proceso
2023-03-13 12:15:53,671 - INFO - Leido el fichero BASE DE DATOS 2022 PRUEBA.xlsx
2023-03-13 12:16:10,057 - INFO - Iniciamos el proceso
2023-03-13 12:16:10,057 - ERROR - [Errno 2] No such file or directory: '/home/sergioretuerto/Documents/Projects/attsf/attsf-ordenes-de-trabajo/app/data/raw/BASE DE DATO 2022 PRUEBA.xlsx'
Traceback (most recent call last):
  File "/home/sergioretuerto/Documents/Projects/attsf/attsf-ordenes-de-trabajo/app/log_example.py", line 10, in <module>
    df_camiones = pd.read_excel(
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 482, in read_excel
    io = ExcelFile(io, storage_options=storage_options, engine=engine)
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1652, in __init__
    ext = inspect_excel_format(
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/io/excel/_base.py", line 1525, in inspect_excel_format
    with get_handle(
  File "/home/sergioretuerto/Documents/Programs/Python/venv/env/lib/python3.10/site-packages/pandas/io/common.py", line 865, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/sergioretuerto/Documents/Projects/attsf/attsf-ordenes-de-trabajo/app/data/raw/BASE DE DATO 2022 PRUEBA.xlsx'
2023-03-13 12:26:31,554 - INFO - Iniciamos el proceso
2023-03-13 12:26:31,554 - ERROR - Fichero no encontrado
2023-03-13 12:31:01,861 - INFO - Iniciamos el proceso
2023-03-13 12:31:01,863 - ERROR - Fichero no encontrado. <class 'FileNotFoundError'>
2023-03-13 12:31:16,562 - INFO - Iniciamos el proceso
2023-03-13 12:31:16,563 - ERROR - Fichero no encontrado. [Errno 2] No such file or directory: '/home/sergioretuerto/Documents/Projects/attsf/attsf-ordenes-de-trabajo/app/data/raw/BASE DE DATO 2022 PRUEBA.xlsx'
2023-03-13 12:37:53,863 - INFO - Iniciamos el proceso
2023-03-13 12:37:53,864 - ERROR - Fichero [Errno 2] No such file or directory: '/home/sergioretuerto/Documents/Projects/attsf/attsf-ordenes-de-trabajo/app/data/raw/BASE DE DATO 2022 PRUEBA.xlsx' no encontrado
2023-03-13 12:40:02,060 - INFO - Iniciamos el proceso
2023-03-13 12:40:02,060 - ERROR - Fichero no encontrado: [Errno 2] No such file or directory: '/home/sergioretuerto/Documents/Projects/attsf/attsf-ordenes-de-trabajo/app/data/raw/BASE DE DATO 2022 PRUEBA.xlsx'
2023-03-13 12:40:45,320 - INFO - Iniciamos el proceso
2023-03-13 12:40:45,322 - ERROR - Fichero no encontrado: [Errno 2] No such file or directory: '/home/sergioretuerto/Documents/Projects/attsf/attsf-ordenes-de-trabajo/app/data/raw/BASE DE DATO 2022 PRUEBA.xlsx'
2023-03-13 12:40:45,322 - INFO - Generando otro df porque el otro no se encuentra
2023-03-13 12:40:58,438 - INFO - Iniciamos el proceso
2023-03-13 12:40:58,439 - ERROR - Fichero no encontrado: [Errno 2] No such file or directory: '/home/sergioretuerto/Documents/Projects/attsf/attsf-ordenes-de-trabajo/app/data/raw/BASE DE DATO 2022 PRUEBA.xlsx'
2023-03-13 12:40:58,439 - INFO - Generando otro df porque el otro no se encuentra
2023-03-13 12:40:58,439 - ERROR - DataFrame.__init__() got an unexpected keyword argument 'columnas'
2023-03-13 12:41:33,506 - INFO - Iniciamos el proceso
2023-03-13 12:41:33,507 - ERROR - Fichero no encontrado: [Errno 2] No such file or directory: '/home/sergioretuerto/Documents/Projects/attsf/attsf-ordenes-de-trabajo/app/data/raw/BASE DE DATO 2022 PRUEBA.xlsx'
2023-03-13 12:41:33,508 - INFO - Generando otro df porque el otro no se encuentra
2023-03-13 12:41:33,508 - ERROR - DataFrame.__init__() got an unexpected keyword argument 'columnas'
2023-03-13 12:42:29,021 - INFO - Iniciamos el proceso
2023-03-13 12:42:29,021 - ERROR - Fichero no encontrado: [Errno 2] No such file or directory: '/home/sergioretuerto/Documents/Projects/attsf/attsf-ordenes-de-trabajo/app/data/raw/BASE DE DATO 2022 PRUEBA.xlsx'
2023-03-13 12:42:29,021 - INFO - Generando otro df porque el otro no se encuentra
2023-03-13 12:42:29,021 - ERROR - Hay un error en los parámetros de lectura: DataFrame.__init__() got an unexpected keyword argument 'columnas'
2023-03-13 12:42:48,722 - INFO - Iniciamos el proceso
2023-03-13 12:42:48,724 - ERROR - Fichero no encontrado: [Errno 2] No such file or directory: '/home/sergioretuerto/Documents/Projects/attsf/attsf-ordenes-de-trabajo/app/data/raw/BASE DE DATO 2022 PRUEBA.xlsx'
2023-03-13 12:42:48,724 - INFO - Generando otro df porque el otro no se encuentra
2023-03-13 12:42:48,724 - ERROR - Hay un error en los parámetros de lectura: DataFrame.__init__() got an unexpected keyword argument 'columnas'
2023-04-12 11:47:38,201 - INFO - Inicio ETL Distribucion
2023-04-12 11:47:38,201 - INFO - Inicio ETL Distribucion
2023-04-12 12:12:03,959 - INFO - Inicio ETL Distribucion
2023-04-12 12:12:03,959 - INFO - Inicio ETL Distribucion
2023-04-12 12:12:44,764 - INFO - Inicio ETL Distribucion
2023-04-12 12:12:44,764 - INFO - Inicio ETL Distribucion
2023-04-12 12:16:02,247 - INFO - Inicio ETL Distribucion
2023-04-12 12:16:02,247 - INFO - Inicio ETL Distribucion
2023-04-12 12:16:44,569 - INFO - Inicio ETL Distribucion
2023-04-12 12:16:44,569 - INFO - Inicio ETL Distribucion
2023-04-12 12:17:01,522 - INFO - Inicio ETL Distribucion
2023-04-12 12:17:01,522 - INFO - Inicio ETL Distribucion
2023-04-12 12:17:19,517 - INFO - Inicio ETL Distribucion
2023-04-12 12:17:19,517 - INFO - Inicio ETL Distribucion
2023-04-12 13:17:38,421 - INFO - Inicio ETL Distribucion
2023-04-12 13:17:38,421 - INFO - Inicio ETL Distribucion
2023-04-12 13:18:10,574 - INFO - Fin ETL Distribucion
2023-04-12 13:18:10,574 - INFO - Fin ETL Distribucion
2023-04-12 13:19:28,105 - INFO - Inicio ETL Distribucion
2023-04-12 13:19:28,105 - INFO - Inicio ETL Distribucion
2023-04-12 13:19:41,700 - INFO - Inicio ETL Distribucion
2023-04-12 13:19:41,700 - INFO - Inicio ETL Distribucion
2023-04-12 13:33:47,265 - INFO - Inicio ETL Distribucion
2023-04-12 13:33:47,265 - INFO - Inicio ETL Distribucion
2023-04-12 13:37:36,679 - INFO - Inicio ETL Distribucion
2023-04-12 13:37:36,679 - INFO - Inicio ETL Distribucion
2023-04-13 10:42:34,484 - INFO - Inicio ETL Distribucion
2023-04-13 10:42:34,484 - INFO - Inicio ETL Distribucion
2023-04-13 11:47:00,755 - INFO - Inicio ETL Distribucion
2023-04-13 11:47:00,755 - INFO - Inicio ETL Distribucion
2023-04-13 11:47:58,956 - INFO - Inicio ETL Distribucion
2023-04-13 11:47:58,956 - INFO - Inicio ETL Distribucion
2023-04-13 11:49:03,786 - INFO - Inicio ETL Distribucion
2023-04-13 11:49:03,786 - INFO - Inicio ETL Distribucion
2023-04-13 12:11:51,485 - INFO - Inicio ETL Distribucion
2023-04-13 12:11:51,485 - INFO - Inicio ETL Distribucion
2023-04-13 12:13:07,624 - INFO - Inicio ETL Distribucion
2023-04-13 12:13:07,624 - INFO - Inicio ETL Distribucion
2023-04-13 12:14:03,154 - INFO - Inicio ETL Distribucion
2023-04-13 12:14:03,154 - INFO - Inicio ETL Distribucion
2023-04-13 12:14:30,795 - INFO - Inicio ETL Distribucion
2023-04-13 12:14:30,795 - INFO - Inicio ETL Distribucion
